<?php

return array(
	'version' => '0.9.4.1',
	'plugin.type' => '',
	'pgcache.enabled' => false,
	'pgcache.engine' => 'file_generic',
	'minify.enabled' => false,
	'minify.auto' => true,
	'minify.engine' => 'file',
	'minify.html.engine' => 'html',
	'minify.js.engine' => 'js',
	'minify.css.engine' => 'csstidy',
	'dbcache.enabled' => false,
	'dbcache.engine' => 'file',
	'objectcache.enabled' => false,
	'objectcache.engine' => 'file',
	'browsercache.enabled' => true,
	'cdn.enabled' => false,
	'cdn.engine' => 'mirror',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'newrelic.enabled' => false,
	'newrelic.api_key' => '',
	'newrelic.account_id' => '',
	'newrelic.appname' => '',
	'newrelic.application_id' => 0,
	'plugin.license_key' => '',
	'widget.pagespeed.enabled' => false,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'common.instance_id' => 1986904212,
	'minify.rewrite' => true,
	'minify.reject.logged' => false,
	'minify.html.enable' => false,
	'minify.html.inline.css' => true,
	'minify.html.inline.js' => true,
	'minify.html.reject.feed' => false,
	'minify.html.strip.crlf' => false,
	'minify.html.comments.ignore' => array(
		0 => 'google_ad_',
		1 => 'RSPEAK_',
	),
	'minify.js.enable' => false,
	'minify.js.combine.header' => true,
	'minify.js.header.embed_type' => 'blocking',
	'minify.js.combine.body' => false,
	'minify.js.body.embed_type' => 'blocking',
	'minify.js.combine.footer' => false,
	'minify.js.footer.embed_type' => 'blocking',
	'minify.js.strip.comments' => false,
	'minify.js.strip.crlf' => false,
	'minify.css.enable' => true,
	'minify.css.combine' => true,
	'minify.css.strip.comments' => false,
	'minify.css.strip.crlf' => false,
	'minify.css.imports' => '',
	'minify.lifetime' => 86400,
	'minify.file.gc' => 86400,
	'minify.reject.uri' => array(
		0 => '',
	),
	'minify.reject.files.js' => array(
		0 => '',
	),
	'minify.reject.files.css' => array(
		0 => '/wp-content/plugins/top3jps-le/top3jps-le.css?ver=4.0.1',
	),
	'minify.reject.ua' => array(
		0 => '',
	),
	'minify.js.groups' => array(
	),
	'minify.css.groups' => array(
	),
	'config.path' => '',
	'common.support' => 'footer',
	'common.tweeted' => false,
	'minify.auto.disable_filename_length_test' => true,
	'minify.cache.files' => array(
		0 => 'https://ajax.googleapis.com',
	),
	'browsercache.replace.exceptions' => array(
		0 => '',
	),
	'browsercache.no404wp' => false,
	'browsercache.no404wp.exceptions' => array(
		0 => 'robots\\.txt',
		1 => '[a-z0-9_\\-]*sitemap[a-z0-9_\\-]*\\.(xml|xsl|html)(\\.gz)?',
	),
	'browsercache.cssjs.expires' => false,
	'browsercache.cssjs.lifetime' => 600,
	'browsercache.cssjs.cache.control' => true,
	'browsercache.cssjs.cache.policy' => 'cache_public_maxage',
	'browsercache.cssjs.etag' => true,
	'browsercache.cssjs.w3tc' => true,
	'browsercache.cssjs.compression' => false,
	'browsercache.cssjs.replace' => false,
	'browsercache.cssjs.nocookies' => false,
	'browsercache.html.expires' => false,
	'browsercache.html.lifetime' => 60,
	'browsercache.html.cache.control' => true,
	'browsercache.html.cache.policy' => 'cache_public_maxage',
	'browsercache.html.etag' => true,
	'browsercache.html.w3tc' => false,
	'browsercache.html.compression' => false,
	'browsercache.other.expires' => true,
	'browsercache.other.lifetime' => 31536000,
	'browsercache.other.cache.control' => false,
	'browsercache.other.cache.policy' => 'cache_public_maxage',
	'browsercache.other.etag' => false,
	'browsercache.other.w3tc' => false,
	'browsercache.other.compression' => true,
	'browsercache.other.replace' => false,
	'browsercache.other.nocookies' => false,
	'browsercache.timestamp' => '1427917615',
	'minify.debug' => false,
	'notes.need_empty_minify' => false,
	'pgcache.cache.home' => false,
	'pgcache.cache.feed' => false,
	'pgcache.cache.ssl' => false,
	'pgcache.cache.404' => false,
	'pgcache.check.domain' => false,
	'pgcache.reject.logged' => true,
	'pgcache.reject.logged_roles' => false,
	'pgcache.reject.roles' => array(
		0 => '',
	),
	'pgcache.prime.enabled' => false,
	'pgcache.prime.interval' => 900,
	'pgcache.prime.limit' => 10,
	'pgcache.prime.sitemap' => '',
	'pgcache.prime.post.enabled' => false,
	'pgcache.purge.home' => true,
	'pgcache.purge.post' => true,
	'pgcache.purge.feed.blog' => true,
	'pgcache.purge.comments' => false,
	'pgcache.purge.author' => false,
	'pgcache.purge.terms' => false,
	'pgcache.purge.feed.comments' => false,
	'pgcache.purge.feed.author' => false,
	'pgcache.purge.feed.terms' => false,
	'pgcache.purge.archive.daily' => false,
	'pgcache.purge.archive.monthly' => false,
	'pgcache.purge.archive.yearly' => false,
	'pgcache.purge.feed.types' => array(
		0 => 'rss2',
	),
	'pgcache.purge.postpages_limit' => 10,
	'pgcache.purge.pages' => array(
		0 => '',
	),
	'pgcache.purge.sitemap_regex' => '([a-z0-9_\\-]*?)sitemap([a-z0-9_\\-]*)?\\.xml',
	'pgcache.late_init' => false,
	'pgcache.compatibility' => false,
	'pgcache.file.gc' => 3600,
	'pgcache.comment_cookie_ttl' => 1800,
	'pgcache.accept.qs' => array(
		0 => '',
	),
	'pgcache.reject.ua' => array(
		0 => '',
	),
	'pgcache.reject.cookie' => array(
		0 => 'wptouch_switch_toggle',
	),
	'pgcache.reject.uri' => array(
		0 => 'wp-.*\\.php',
		1 => 'index\\.php',
	),
	'pgcache.accept.files' => array(
		0 => 'wp-comments-popup.php',
		1 => 'wp-links-opml.php',
		2 => 'wp-locations.php',
	),
	'pgcache.accept.uri' => array(
		0 => 'sitemap(_index)?\\.xml(\\.gz)?',
		1 => '([a-z0-9_\\-]+)?sitemap\\.xsl',
		2 => '[a-z0-9_\\-]+-sitemap([0-9]+)?\\.xml(\\.gz)?',
	),
	'notes.plugins_updated' => false,
	'extensions.active' => array(
	),
	'extensions.settings' => array(
		'genesis.theme' => array(
			'wp_head' => '0',
			'genesis_header' => '1',
			'genesis_do_nav' => '0',
			'genesis_do_subnav' => '0',
			'loop_front_page' => '1',
			'loop_terms' => '1',
			'flush_terms' => '1',
			'loop_single' => '1',
			'loop_single_excluded' => '',
			'loop_single_genesis_comments' => '0',
			'loop_single_genesis_pings' => '0',
			'sidebar' => '0',
			'sidebar_excluded' => '',
			'genesis_footer' => '1',
			'wp_footer' => '0',
			'reject_logged_roles' => '1',
			'reject_logged_roles_on_actions' => array(
				0 => 'genesis_loop',
				1 => 'wp_head',
				2 => 'wp_footer',
			),
			'reject_roles' => array(
				0 => 'administrator',
			),
		),
		'feedburner' => array(
			'urls' => '',
		),
		'cloudflare' => array(
			'enabled' => '1',
			'email' => '',
			'key' => '',
			'zone' => '',
			'ips.ip4' => array(
				0 => '199.27.128.0/21',
				1 => '173.245.48.0/20',
				2 => '103.21.244.0/22',
				3 => '103.22.200.0/22',
				4 => '103.31.4.0/22',
				5 => '141.101.64.0/18',
				6 => '108.162.192.0/18',
				7 => '190.93.240.0/20',
				8 => '188.114.96.0/20',
				9 => '197.234.240.0/22',
				10 => '198.41.128.0/17',
				11 => '162.158.0.0/15',
				12 => '104.16.0.0/12',
			),
			'ips.ip6' => array(
				0 => '2400:cb00::/32',
				1 => '2606:4700::/32',
				2 => '2803:f800::/32',
				3 => '2405:b500::/32',
				4 => '2405:8100::/32',
			),
		),
	),
	'cdn.uploads.enable' => true,
	'cdn.includes.enable' => true,
	'cdn.theme.enable' => true,
	'cdn.minify.enable' => true,
	'cdn.custom.enable' => true,
	'cdn.import.external' => false,
	'cdn.canonical_header' => false,
	'cdn.mirror.ssl' => 'auto',
	'cdn.reject.ssl' => false,
	'cdn.reject.logged_roles' => false,
	'cdn.reject.roles' => array(
		0 => '',
	),
	'cdn.includes.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.xml',
	'cdn.theme.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.ico;*.ttf;*.otf,*.woff,*.less',
	'cdn.import.files' => '',
	'cdn.custom.files' => array(
		0 => 'favicon.ico',
		1 => '{wp_content_dir}/gallery/*',
		2 => '{wp_content_dir}/uploads/avatars/*',
		3 => '{plugins_dir}/wordpress-seo/css/xml-sitemap.xsl',
		4 => '{plugins_dir}/wp-minify/min*',
		5 => '{plugins_dir}/*.js',
		6 => '{plugins_dir}/*.css',
		7 => '{plugins_dir}/*.gif',
		8 => '{plugins_dir}/*.jpg',
		9 => '{plugins_dir}/*.png',
	),
	'cdn.reject.ua' => array(
		0 => '',
	),
	'cdn.reject.files' => array(
		0 => '{uploads_dir}/wpcf7_captcha/*',
		1 => '{uploads_dir}/imagerotator.swf',
		2 => '{plugins_dir}/wp-fb-autoconnect/facebook-platform/channel.html',
	),
	'cdn.mirror.domain' => array(
		0 => 'd1xyja5tz2ivlb.cloudfront.net',
	),
	'cdn.debug' => false,
	'minify.auto.filename_length' => 150,
	'minify.csstidy.options.remove_bslash' => false,
	'minify.csstidy.options.compress_colors' => false,
	'minify.csstidy.options.compress_font-weight' => false,
	'minify.csstidy.options.lowercase_s' => false,
	'minify.csstidy.options.remove_last_;' => false,
	'minify.csstidy.options.sort_properties' => false,
	'minify.csstidy.options.sort_selectors' => false,
	'minify.csstidy.options.discard_invalid_properties' => false,
	'minify.csstidy.options.css_level' => 'CSS2.1',
	'minify.csstidy.options.preserve_css' => false,
	'minify.csstidy.options.timestamp' => false,
	'minify.csstidy.options.template' => 'default',
	'minify.csstidy.options.optimise_shorthands' => 1,
	'minify.csstidy.options.case_properties' => 1,
	'minify.csstidy.options.merge_selectors' => 2,
);