<?php
function get_mod_optimizer_config( &$pb1lbp ) {
	$pb1lbp = array(
		"permalink"           => array(
			"count"          => 0,
			"prefer_article" => FALSE_BOOL_DEFINE,
			"label"          => __( "Permalink", PluginTextDomain_DEFINE ),
			"base"           => 016,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => FALSE_BOOL_DEFINE,
			"alert"          => "",
			"priority"       => "",
			"info"           => array(
				"desc"            => __( "Keep your permalinks as short as possible with your keyword or partial keyword at or near the beginning", PluginTextDomain_DEFINE ),
				"exact"           => "",
				"partial"         => "",
				"no_match"        => "",
				"preview_penalty" => "",
				"color_overload"  => "",
			),
		),
		"meta_title"          => array(
			"count"          => 0,
			"prefer_article" => FALSE_BOOL_DEFINE,
			"label"          => __( "META Title", PluginTextDomain_DEFINE ),
			"base"           => 044,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => FALSE_BOOL_DEFINE,
			"alert"          => "",
			"priority"       => "",
			"info"           => array(
				"desc"            => __( "Ensure your exact keyword appears at or near the beginning of the META title", PluginTextDomain_DEFINE ),
				"exact"           => "",
				"partial"         => "",
				"no_match"        => "",
				"preview_penalty" => "",
				"color_overload"  => "",
			),
		),
		"meta_description"    => array(
			"count"          => 0,
			"prefer_article" => FALSE_BOOL_DEFINE,
			"label"          => __( "META Description", PluginTextDomain_DEFINE ),
			"base"           => 016,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => FALSE_BOOL_DEFINE,
			"alert"          => "",
			"priority"       => "",
			"info"           => array(
				"desc"            => __( "Use text that encourages people to click on your search listing and use your exact keyword and other words related to it", PluginTextDomain_DEFINE ),
				"exact"           => "",
				"partial"         => "",
				"no_match"        => "",
				"preview_penalty" => "",
				"color_overload"  => "",
			),
		),
		"meta_headings"       => array(
			"count"          => 0,
			"prefer_article" => FALSE_BOOL_DEFINE,
			"label"          => __( "Headings", PluginTextDomain_DEFINE ),
			"base"           => 014,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => FALSE_BOOL_DEFINE,
			"alert"          => "",
			"priority"       => "",
			"info"           => array(
				"desc"            => __( "Ensure your keyword or a variation appears in your H1 title (Usually your post title but some themes use H2 sub-heading for the post title)", PluginTextDomain_DEFINE ),
				"exact"           => "",
				"partial"         => "",
				"no_match"        => "",
				"preview_penalty" => "",
				"color_overload"  => "",
			),
		),
		"meta_sub_headings"   => array(
			"count"          => 0,
			"prefer_article" => FALSE_BOOL_DEFINE,
			"label"          => __( "Sub Headings", PluginTextDomain_DEFINE ),
			"base"           => 012,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => __( "Add sub-headings containing your keyword or variations (H2 or H3 tags)", PluginTextDomain_DEFINE ),
			"alert"          => "",
			"priority"       => "",
			"info"           => array( "desc" => "", "exact" => "", "partial" => "", "no_match" => "", "preview_penalty" => "", "color_overload" => "", ),
		),
		"meta_links_internal" => array(
			"count"          => 0,
			"prefer_article" => TRUE_BOOL_DEFINE,
			"label"          => __( "Internal Links", PluginTextDomain_DEFINE ),
			"base"           => 014,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => FALSE_BOOL_DEFINE,
			"alert"          => "",
			"priority"       => "",
			"info"           => array(
				"desc"            => __( "Use internal links preferably in the main content with anchor text that matches or relates to your keyword", PluginTextDomain_DEFINE ),
				"exact"           => "",
				"partial"         => "",
				"no_match"        => "",
				"preview_penalty" => "",
				"color_overload"  => "",
			),
		),
		"meta_links_outbound" => array(
			"count"          => 0,
			"prefer_article" => TRUE_BOOL_DEFINE,
			"label"          => __( "Outbound Links", PluginTextDomain_DEFINE ),
			"base"           => 014,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => FALSE_BOOL_DEFINE,
			"alert"          => "",
			"priority"       => "",
			"info"           => array(
				"desc"            => __( "Use outbound links preferably in the main content with anchor text that matches or relates to your keyword", PluginTextDomain_DEFINE ),
				"exact"           => "",
				"partial"         => "",
				"no_match"        => "",
				"preview_penalty" => "",
				"color_overload"  => "",
			),
		),
		"meta_img"            => array(
			"count"          => 0,
			"prefer_article" => TRUE_BOOL_DEFINE,
			"label"          => __( "Image ALT tags", PluginTextDomain_DEFINE ),
			"base"           => 6,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => __( "Add your keyword to the ALT tag of an image", PluginTextDomain_DEFINE ),
			"alert"          => "",
			"priority"       => "",
			"info"           => array( "desc" => "", "exact" => "", "partial" => "", "no_match" => "", "preview_penalty" => "", "color_overload" => "", ),
		),
		"meta_video"          => array(
			"count"          => 0,
			"prefer_article" => TRUE_BOOL_DEFINE,
			"label"          => __( "Video Embed", PluginTextDomain_DEFINE ),
			"base"           => 6,
			"normal"         => 0,
			"score"          => 0,
			"normal_score"   => 0,
			"display"        => TRUE_BOOL_DEFINE,
			"suggest"        => __( "Embed a video in your main content, this helps keep visitors on your page for longer", PluginTextDomain_DEFINE ),
			"alert"          => "",
			"priority"       => "",
			"info"           => array( "desc" => "", "exact" => "", "partial" => "", "no_match" => "", "preview_penalty" => "", "color_overload" => "", ),
		),
	);
}

?>